
# ----- Application Settings -----
[App]
is_test = False
width = 320
height = 480
font = DejaVu Sans
font_size = 10
space_edge = 3
space_between = 3
border = 2

# ----- Screen Settings -----
[Screen1]
bg_color = SlateGray2

[Screen2]
bg_color = light blue

# ----- Widget Settings -----
[Header Widget]
bg_color = light gray
bar_height = 40
font_size_clock = 18

[Weather Widget]
api_key = ad2af80e13ff2d4c604e9085e3f718eb
lat = 51.3087
lon = -2.4991
height = 215
width = 160
icon_size = 65

[Rain Widget]
lat = 51.3087
lon = -2.4991
px_w = 314 
px_h =  374

[Calendar Widget]
height = 157

